//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp5.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e2dcdb3b85d1a123bfc2afb2842fc959.
        /// </summary>
        internal static string APIKEY {
            get {
                return ResourceManager.GetString("APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumbai.
        /// </summary>
        internal static string City1 {
            get {
                return ResourceManager.GetString("City1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delhi.
        /// </summary>
        internal static string City2 {
            get {
                return ResourceManager.GetString("City2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolkata.
        /// </summary>
        internal static string City3 {
            get {
                return ResourceManager.GetString("City3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chennai.
        /// </summary>
        internal static string City4 {
            get {
                return ResourceManager.GetString("City4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangalore.
        /// </summary>
        internal static string City5 {
            get {
                return ResourceManager.GetString("City5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one city.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick.
        /// </summary>
        internal static string Tick {
            get {
                return ResourceManager.GetString("Tick", resourceCulture);
            }
        }
    }
}
